version: 2

models:
  - name: int_order_items_products
    columns:
      - name: product_category_name
        tests:
          - not_null:
              severity: warn  # Benar: severity berada di dalam not_null

  - name: int_order_enriched
    columns:
      - name: purchase_time_segment
        tests:
          - accepted_values:
              values: ['Dawn', 'Morning', 'Afternoon', 'Night']
              severity: warn 

  - name: int_seller_performance
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null